BlazorWebView
dotnet/docs-maui pull request #134
Opened 2021-08-23 14:08 UTC by davidbritch

Fixes #12

2021-09-17 23:48 UTC, danroth27 commented
@Eilon Can you take a look at these BlazorWebView docs?

2021-09-20 17:23 UTC, Eilon requested changes

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +This project template creates a multi-targeted .NET MAUI Blazor app that can be deployed to Android, iOS, Mac Catalyst, and Windows. The `BlazorWebControl` is defined in *MainPage.xaml* in the create
```suggestion
This project template creates a multi-targeted .NET MAUI Blazor app that can be deployed to Android, iOS, Mac Catalyst, and Windows. The `BlazorWebView` is defined in *MainPage.xaml* in the created project, and points to the root of the Blazor app:
```

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +This project template creates a multi-targeted .NET MAUI Blazor app that can be deployed to Android, iOS, Mac Catalyst, and Windows. The `BlazorWebControl` is defined in *MainPage.xaml* in the create
Another comment: Here it says `Mac Catalyst` but that's more of the app architecture, not the platform per se. The _platform_ is macOS. This is often discussed throughout MAUI in terms of where should it say Mac Catalyst / WinUI and where should it say macOS / Windows.

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +The root Blazor component for the app is in *Main.razor*. The rest of the Blazor components are in the *Pages* and *Shared* project folders, and are identical to the components used in the default Bl
```suggestion
The root Blazor component for the app is in *Main.razor*, which Razor compiles into a type named `Main` in the application's root namespace. The rest of the Blazor components are in the *Pages* and *Shared* project folders, and are identical to the components used in the default Blazor web template. Static web assets for the app are in the *wwwroot* folder.
```

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +1. Add the Razor SDK, `Microsoft.NET.Sdk.Razor` to your project by editing its first line:
```suggestion
1. Add the Razor SDK, `Microsoft.NET.Sdk.Razor` to your project by editing its first line of the CSPROJ project file:
```

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +1. Modify the `Configure` method of your `Startup` class to register the `BlazorWebView` control for use in your app. To do this, call the `RegisterBlazorMauiWebView` method, the `UseMicrosoftExtensi
I think `UseMicrosoftExtensionsServiceProviderFactory` is gone now, or at least not needed.

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +                        .UseMicrosoftExtensionsServiceProviderFactory()
Remove `UseMicrosoftExtensionsServiceProviderFactory`.

2021-09-20 17:23 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +    public class Startup : IStartup
This pattern changed and `Startup` is gone and replaced with `MauiProgram`. Please update this section to match what's in a new MAUI Blazor app, which is somewhat different from previous previews.

2021-09-21 18:53 UTC, Eilon requested changes
One new comment, plus some other earlier pending comments. Looking good!

2021-09-21 18:53 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +> Using the `BlazorWebView` control requires you to have installed the ASP.NET and web development workload in Visual Studio. In addition, to use the `BlazorWebView` control on Windows requires you t
Apparently VS2022 now has WebView2 already installed as a component, so there is no extra step for this anymore.

2021-10-26 16:02 UTC, Eilon requested changes

2021-10-26 16:02 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +> Using the `BlazorWebView` control requires you to have installed the ASP.NET and web development workload in Visual Studio. In addition, to use the `BlazorWebView` control on Windows requires you t
Oh actually I think keeping some verbiage similar to this can be important. So for the developer _building_ the app this shouldn't be a problem because VS2022 installs WebView2. But for a user just _running_ the app, they would need to make sure they have WebView2 installed. So maybe this section could be changed to emphasize the importance to an end-user, as opposed to the developer?

2021-12-08 12:48 UTC, davidbritch commented
@Eilon 

Closing here, and created a new [PR](#231) that merges into the release branch.

2021-12-08 12:49 UTC, closed without merging