Update Installation Instructions for VS Code .NET MAUI Extension
dotnet/docs-maui pull request #2033
Opened 2024-01-23 18:25 UTC by applejax124

- Updated the instructions for installing the .NET MAUI Extension for VS Code including all dependencies, workloads, and target platforms. 
- Added clarification for setting up android as a target platform on all operating systems.

2024-01-23 18:26 UTC, applejax124 commented
@BethMassi @maddymontaquila - Could you please review and give feedback on this PR? Thank you!

2024-01-23 19:38 UTC, applejax124 commented
@jonpryor - Could you please review as well? Thank you!

2024-01-23 22:13 UTC, BethMassi approved these changes

2024-01-24 15:54 UTC, davidbritch requested changes
All minor nit picks :)

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +    1. On Windows, it is recommended to use the Visual Studio installer to manage .NET and the .NET MAUI workload installations. Instructions on using the Visual Studio installer can be found [here](
```suggestion
    On Windows, it's recommended to use the Visual Studio installer to manage .NET and the .NET MAUI workload installations. Instructions on using the Visual Studio installer can be found [here](./installation.md?tabs=vswin).
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +1. Install .NET MAUI workload
```suggestion
1. Install the .NET MAUI workload:
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +    - Windows/MacOS: Run `dotnet workload install maui` in a terminal.
```suggestion
    On Windows and macOS, run the following command in a terminal: 
    
    ```cmd
    dotnet workload install maui
    ```
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +    - Linux: Run `dotnet workload install maui-android` in a terminal.
```suggestion
    On Linux, run the following command in a terminal:
    
    ```cmd
    dotnet workload install maui-android
    ```
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +## Set up Target Platforms
```suggestion
## Set up target platforms
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +To debug a .NET MAUI app in Visual Studio code, you need to have a valid target platform based on your development machine's operating system:
```suggestion
To debug a .NET MAUI app in Visual Studio Code, you need to have a valid target platform for your development machine's operating system:
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +### iOS and MacOS
```suggestion
### iOS and macOS
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +To debug to an iOS or MacOS target in Visual Studio Code, follow the steps below:
```suggestion
To debug to an iOS or macOS target in Visual Studio Code:
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +To debug to an Android target in Visual Studio Code, follow the steps below:
```suggestion
To debug to an Android target in Visual Studio Code:
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +1. Install the Android SDK via one of the following options:
```suggestion
1. Install the Android SDK via one of the following approaches:
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +#### Using "InstallAndroidDependencies"
```suggestion
#### Using the InstallAndroidDependencies target
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +    * **(Recommended)** Create a new .NET MAUI project (`dotnet new maui`) and use the [InstallAndroidDependencies target](#using-installandroiddependencies).
```suggestion
    * **(Recommended)** Create a new .NET MAUI project (`dotnet new maui`) and use the [InstallAndroidDependencies target](#using-the-installandroiddependencies-target).
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +> `dotnet build -t:InstallAndroidDependencies -f:net8.0-android -p:AndroidSdkDirectory "<AndroidSdkPath>" -p:JavaSdkDirectory "<JavaSdkPath>" -p:AcceptAndroidSDKLicenses=True`
```suggestion
```cmd
dotnet build -t:InstallAndroidDependencies -f:net8.0-android -p:AndroidSdkDirectory "<AndroidSdkPath>" -p:JavaSdkDirectory "<JavaSdkPath>" -p:AcceptAndroidSDKLicenses=True
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +* `AndroidSdkDirectory "<AndroidSdkPath>"` : installs or updates Android dependencies to the specified path (Note: Must use an absolute path).
```suggestion
In the command above:
* `AndroidSdkDirectory "<AndroidSdkPath>"`: installs or updates Android dependencies to the specified absolute path.
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +* `JavaSdkDirectory "<JavaSdkPath>"` : installs Java to the specified path (Note: Must be an absolute path).
```suggestion
* `JavaSdkDirectory "<JavaSdkPath>"`: installs Java to the specified absolute path.
```

2024-01-24 15:54 UTC, davidbritch commented on docs/get-started/installation.md
> +* `AcceptAndroidSDKLicenses=True` : accepts the necessary Android licenses for development.
```suggestion
* `AcceptAndroidSDKLicenses=True`: accepts the required Android licenses for development.
```

2024-01-25 11:42 UTC, davidbritch approved these changes

2024-01-25 11:45 UTC, merged