BlazorWebView
dotnet/docs-maui pull request #231
Opened 2021-12-08 12:47 UTC by davidbritch

Replaces #134 

Fixes #12

2021-12-08 17:56 UTC, Eilon requested changes
Just 2 small comments and then I think it's good to go!

2021-12-08 17:56 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +    > Blazor requires service scopes, which are only supported with the `Microsoft.Extensions.DependencyInjection` library.
I think this note is no longer needed; the default MAUI stuff has everything you need.

2021-12-08 17:56 UTC, Eilon commented on docs/user-interface/controls/blazorwebview.md
> +    }
No code change, just making indentation consistent:

```suggestion
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .RegisterBlazorMauiWebView()
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddBlazorWebView();
            // Register any app services on the IServiceCollection object
            // e.g. builder.Services.AddSingleton<WeatherForecastService>();

            return builder.Build();
        }
    }
```

2021-12-08 18:20 UTC, Eilon approved these changes
Ship it!

2021-12-08 18:21 UTC, Eilon commented
Apparently my review isn't good enough to approve ☹️ Who can give me more permission in this repo? I'll probably end up writing a doc or two as well.

2021-12-09 10:23 UTC, davidbritch commented
@Eilon I've given you write access.

Docs require an admin to merge them, so I can do it.

2021-12-09 17:24 UTC, Eilon commented
Perfect! Let's get this published! 😄

2021-12-13 10:22 UTC, merged