Link to .NET Upgrade Assistant from MAUI migration doc
dotnet/docs-maui pull request #344
Opened 2022-03-14 15:25 UTC by danroth27

2022-03-15 09:05 UTC, davidbritch commented
@danroth27 I'm against merging this PR. Linking to a marketing doc from a technical doc is never a good idea. I get that the current migration doc isn't helpful, but it was never intended to be the final doc. It's literally what was published last summer, and will be replaced for GA.

2022-03-15 15:30 UTC, danroth27 commented
> @danroth27 I'm against merging this PR. Linking to a marketing doc from a technical doc is never a good idea. I get that the current migration doc isn't helpful, but it was never intended to be the final doc. It's literally what was published last summer, and will be replaced for GA.

The purpose of adding the link is to point users to instructions on how to actual run the .NET Upgrade Assistant as directed. We could point to https://docs.microsoft.com/dotnet/core/porting/upgrade-assistant-overview instead.

2022-03-15 15:30 UTC, danroth27 commented on docs/get-started/migrate.md
> +1. Use the [.NET Upgrade Assistant](https://dotnet.microsoft.com/platform/upgrade-assistant) for .NET MAUI to migrate your Xamarin.Forms projects to .NET MAUI single project, and perform well-known c
```suggestion
1. Use the [.NET Upgrade Assistant](https://docs.microsoft.com/dotnet/core/porting/upgrade-assistant-overview) for .NET MAUI to migrate your Xamarin.Forms projects to .NET MAUI single project, and perform well-known code namespace changes.
```

2022-03-16 09:12 UTC, davidbritch requested changes
You need to drop https://docs.microsoft.com from the link. So the link will be: /dotnet/core/porting/upgrade-assistant-overview

2022-03-17 00:14 UTC, danroth27 commented on docs/get-started/migrate.md
> +1. Use the [.NET Upgrade Assistant](https://docs.microsoft.com/dotnet/core/porting/upgrade-assistant-overview) for .NET MAUI to migrate your Xamarin.Forms projects to .NET MAUI single project, and pe
```suggestion
1. Use the [.NET Upgrade Assistant](/dotnet/core/porting/upgrade-assistant-overview) for .NET MAUI to migrate your Xamarin.Forms projects to .NET MAUI single project, and perform well-known code namespace changes.
```

2022-03-17 08:56 UTC, davidbritch approved these changes
Thanks @danroth27

2022-03-17 08:56 UTC, merged