Remove mention of GenerateAppxPackageOnBuild
dotnet/docs-maui pull request #857
Opened 2022-09-06 20:26 UTC by mattleibow

This was a bug before, but now `dotnet publish` is all that is needed. In fact, using that property passes it down to referenced class  libraries and fails the build.

See dotnet/maui#9547

2022-09-08 16:12 UTC, adegeo approved these changes

2022-09-08 16:13 UTC, adegeo commented
@mattleibow is the workaround you detailed in the linked issue still required?

2022-09-08 19:38 UTC, mattleibow commented
Unfortunately yes. We are waiting on the WinUI team: https://github.com/microsoft/WindowsAppSDK/issues/2940

2022-09-13 16:18 UTC, adegeo requested changes
@mattleibow I added more details about the workaround to the doc. Can you verify this? Thanks!

2022-09-14 12:16 UTC, mattleibow reviewed
Looks good!

2022-09-14 16:01 UTC, adegeo approved these changes

2022-09-14 16:01 UTC, merged

2023-01-13 22:56 UTC, mattleibow commented
Moved the WASDK issue to https://github.com/microsoft/WindowsAppSDK/issues/3337